import type { Metadata } from "next";
import { Inter, VT323 } from "next/font/google";
import "./globals.css";

import NavBar from "@/components/layout/navbar";

const inter = Inter({
  subsets: ["latin"],
});

const vt = VT323({
  weight: ['400'],
}); 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${vt.className} antialiased`}
      >
        <NavBar />
        <div className="grid grid-cols-1 md:grid-cols-[200_1fr] gap-4 p-4">
          <div className={`md:col-start-2 md:col-end-3 text-3xl`}>
            {children}
          </div>
        </div>

      </body>
    </html>
  );
}
